#samples.yaml for mutect2.snakefile

base_file_name : DTRCC10

samples: /home/mi724/Tools/Snakemake/Mutect2/bam.list

vcf_files: /home/mi724/Tools/Snakemake/Mutect2/vcf_file.list

f1r2: /home/mi724/Tools/Snakemake/Mutect2/f1r2.list

normals: /home/mi724/Tools/Snakemake/Mutect2/normals.list
  

